version: '3.7'
services:
  frontend:
    container_name: front_circulares
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - circulares

  backend:
    container_name: back_circulares
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/opt'
    ports:
      - "8000:8000"
    networks:
      - circulares

networks:
  circulares:
